address: 127.0.0.1 # Listen address
port: 9348 # Listen port
timeout: 10 # HTTP timeout (in seconds) for Redfish API calls
retries: 1 # Number of retries before a target is marked as unreachable
hosts:
  172.16.33.176:
    username: root
    password: calvin
  default:
    username: root
    password: calvin
metrics:
  - system
  - sensors
  - power
  - sel
  - disks
