{{ if .Values.idracConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idrac-exporter.fullname" . }}-config
  labels:
    {{- include "idrac-exporter.labels" . | nindent 4 }}
stringData:
{{- if default .Values.idracConfigIsTemplate false }}
  idrac.yml.template: {{ tpl .Values.idracConfig . | quote }}
{{- else }}
  idrac.yml: {{ tpl .Values.idracConfig . | quote }}
{{ end }}
{{ end }}